export type GuideChoice = {
  label: string;
  sub?: string;
};

export type GuideStep = {
  phase: "READ" | "MODEL" | "DERIVE" | "CALC" | "JUDGE";
  title: string;
  prompt: string;
  formula?: string;
  choices: GuideChoice[];
  correct: number;
  explanation: string;
  wrongHint: string;
};

export type GuidedQuestion = {
  id: number;
  topic: string;
  title: string;
  image: string;
  solutions: string[];
  finalAnswer: string;
  goal: string;
  steps: GuideStep[];
};

export const GUIDED_QUESTIONS: GuidedQuestion[] = [
  {
    id: 1,
    topic: "生命力・平均寿命",
    title: "死力から生存関数を組み立てる",
    image: "/exam/2025-q2/q1.webp",
    solutions: ["/exam/2025-q2/s1.webp"],
    finalAnswer: "（C）480",
    goal: "死力を積分して生存関数へ戻し、平均寿命の式を作る。",
    steps: [
      {
        phase: "MODEL",
        title: "死力を生存確率へ変換する",
        prompt: "死力 μₛ が与えられたとき、t 年生存確率 ₜp₀ の基本式はどれ？",
        choices: [
          { label: "exp(−∫₀ᵗ μₛ ds)" },
          { label: "1 − ∫₀ᵗ μₛ ds" },
          { label: "exp(∫₀ᵗ μₛ ds)" },
        ],
        correct: 0,
        explanation: "死力は「瞬間的な死亡の強さ」。累積死力を積分し、その負の指数を取ると生存確率になる。",
        wrongHint: "μₛ をそのまま確率として引くのではなく、累積ハザードと生存関数の関係を思い出そう。",
      },
      {
        phase: "DERIVE",
        title: "60歳までの生存関数",
        prompt: "0≤t≤60 で μₜ=1/(α−t)。積分すると ₜp₀ はどれになる？",
        formula: "ₜp₀ = exp{−∫₀ᵗ 1/(α−s) ds}",
        choices: [
          { label: "α/(α−t)" },
          { label: "(α−t)/α" },
          { label: "exp{−t/(α−t)}" },
        ],
        correct: 1,
        explanation: "積分結果は log α−log(α−t)。前にマイナスがあるため、exp{log(α−t)−log α}=(α−t)/α。",
        wrongHint: "log の差を指数関数に戻すとき、分子と分母の向きを確認しよう。",
      },
      {
        phase: "DERIVE",
        title: "60歳以降を接続する",
        prompt: "60<t<100 では、60歳まで生存する確率と60歳以降の条件付生存確率を掛ける。正しい形は？",
        choices: [
          { label: "(α−60)/α × {(100−t)/40}³" },
          { label: "(α−t)/α × {(100−t)/40}³" },
          { label: "(α−60)/α × {40/(100−t)}³" },
        ],
        correct: 0,
        explanation: "ₜp₀=₆₀p₀×ₜ₋₆₀p₆₀。60歳以降の死力3/(100−x)から、条件付生存確率は{(100−t)/40}³になる。",
        wrongHint: "区間をまたぐので、前半は t ではなく境界の60で固定する。",
      },
      {
        phase: "CALC",
        title: "平均寿命65から α を決める",
        prompt: "e̊₀=∫₀¹⁰⁰ ₜp₀dt を前後2区間に分けると、どの式になる？",
        choices: [
          { label: "70 − 2400/α = 65", sub: "したがって α=480" },
          { label: "60 − 1800/α = 65", sub: "したがって α=−360" },
          { label: "70 + 2400/α = 65", sub: "したがって α=−480" },
        ],
        correct: 0,
        explanation: "0〜60歳の積分が60−1800/α、60〜100歳が10−600/α。合計70−2400/α=65より α=480。",
        wrongHint: "平均寿命は生存確率の面積。前半と後半の積分値を足して65と置こう。",
      },
    ],
  },
  {
    id: 2,
    topic: "多重脱退・定常人口",
    title: "率を人数へ戻して連立する",
    image: "/exam/2025-q2/q2.webp",
    solutions: ["/exam/2025-q2/s2.webp", "/exam/2025-q2/s2b.webp"],
    finalAnswer: "①（C）0.0711　②（H）0.00885",
    goal: "死亡・退職を人数の収支式に直し、定常人口の条件と連立する。",
    steps: [
      {
        phase: "READ",
        title: "定常人口 S を配分する",
        prompt: "会社員は自己都合退職者の3倍。年齢区間の定常人口を S とすると、両集団の平均在籍人数は？",
        choices: [
          { label: "会社員 3S/4、退職者 S/4" },
          { label: "会社員 2S/3、退職者 S/3" },
          { label: "会社員 3S、退職者 S" },
        ],
        correct: 0,
        explanation: "比が3:1で合計Sなので、会社員の平均人数は3S/4、退職者はS/4。",
        wrongHint: "「3倍」は3:1。全体を4等分して考えよう。",
      },
      {
        phase: "DERIVE",
        title: "副集団の死亡数を先に決める",
        prompt: "退職者集団の人口収支と絶対死亡率の条件を整理すると、死亡者数 dˣⁱⁱ は？",
        choices: [
          { label: "S/150" },
          { label: "S/300" },
          { label: "2S/151" },
        ],
        correct: 1,
        explanation: "退職者の期首・期末平均S/4と、会社員からの流入 iₓ を含む分母に条件(d)を適用すると dˣⁱⁱ=S/300。",
        wrongHint: "退職者集団には、期中に会社員から移ってくる人数 iₓ がある。単純にS/4へ率を掛けない。",
      },
      {
        phase: "DERIVE",
        title: "残りの人数を連立で回収する",
        prompt: "条件(a)〜(d)と人口収支式を連立した結果として正しい組は？",
        choices: [
          { label: "dˣᵃᵃ=S/150、lˣᵃᵃ=39S/50、iₓ=4S/75" },
          { label: "dˣᵃᵃ=S/100、lˣᵃᵃ=3S/4、iₓ=S/75" },
          { label: "dˣᵃᵃ=S/300、lˣᵃᵃ=18S/25、iₓ=2S/75" },
        ],
        correct: 0,
        explanation: "さらに lˣ₊₁ᵃᵃ=18S/25、lˣⁱⁱ=9S/40、lˣ₊₁ⁱⁱ=11S/40 が得られる。Sは最後に比で消える。",
        wrongHint: "条件(c)から dˣᵃᵃ=lˣᵃᵃ/117。平均人数3S/4の式と組み合わせよう。",
      },
      {
        phase: "CALC",
        title: "① 中央自己都合退職率",
        prompt: "iₓ を会社員の平均在籍人数で割る。計算結果は？",
        formula: "iₓ / {(lˣᵃᵃ+lˣ₊₁ᵃᵃ)/2}",
        choices: [
          { label: "(4/75)/(3/4)=16/225=0.071111…", sub: "選択肢（C）" },
          { label: "(4/75)/(1/4)=16/75=0.213333…" },
          { label: "(1/150)/(3/4)=2/225=0.008888…" },
        ],
        correct: 0,
        explanation: "求める率の分子は死亡者数ではなく、会社員から退職者へ移る人数 iₓ。",
        wrongHint: "①は「自己都合退職率」。分子に置く人数を確認しよう。",
      },
      {
        phase: "CALC",
        title: "② 会社員の絶対死亡率",
        prompt: "自己都合退職との競合を調整した分母で dˣᵃᵃ を割ると？",
        formula: "dˣᵃᵃ / (lˣᵃᵃ − iₓ/2)",
        choices: [
          { label: "1/117=0.008547…" },
          { label: "1/113=0.0088496…", sub: "選択肢（H）" },
          { label: "1/100=0.010000" },
        ],
        correct: 1,
        explanation: "(S/150)/(39S/50−2S/75)=1/113。自己都合退職者は年内一様発生なので半数分を調整する。",
        wrongHint: "分母は lˣᵃᵃ そのものではなく、iₓ/2 を引いた人数。",
      },
    ],
  },
  {
    id: 3,
    topic: "年金・計算基数",
    title: "公式を定義へ戻して判定する",
    image: "/exam/2025-q2/q3.webp",
    solutions: ["/exam/2025-q2/s3.webp"],
    finalAnswer: "（A）（C）（D）",
    goal: "開始時点・支払回数・添字を一つずつ検算する。",
    steps: [
      {
        phase: "JUDGE",
        title: "式（A）を判定",
        prompt: "f年据置・期末払n年定期生命年金の式（A）は正しい？",
        choices: [{ label: "正しい" }, { label: "誤り" }],
        correct: 0,
        explanation: "支払時点は f+1 から f+n。したがって分子は Nₓ₊f₊₁−Nₓ₊f₊n₊₁ となり、式（A）は正しい。",
        wrongHint: "期末払の最初の支払いが、加入時点から何年後かを数えよう。",
      },
      {
        phase: "JUDGE",
        title: "式（B）を判定",
        prompt: "年k回払・期始払生命年金の和の前に、必要な係数は？",
        choices: [
          { label: "1/k が必要なので（B）は誤り" },
          { label: "係数は不要なので（B）は正しい" },
          { label: "k が必要なので（B）は誤り" },
        ],
        correct: 0,
        explanation: "1回の支払額は年額1の1/k。正しくは (1/k)Σₜ₌₀ⁿᵏ⁻¹vᵗ⁄ᵏ·ₜ⁄ₖpₓ。",
        wrongHint: "年k回で年額1なら、各回の支払額はいくらかを確認しよう。",
      },
      {
        phase: "JUDGE",
        title: "式（C）を判定",
        prompt: "Cₓ=vDₓ−Dₓ₊₁ は正しい？",
        choices: [{ label: "正しい" }, { label: "誤り" }],
        correct: 0,
        explanation: "Cₓ=vˣ⁺¹dₓ=vˣ⁺¹(lₓ−lₓ₊₁)=vDₓ−Dₓ₊₁。",
        wrongHint: "Dₓ=vˣlₓ、Cₓ=vˣ⁺¹dₓ を直接代入してみよう。",
      },
      {
        phase: "JUDGE",
        title: "式（D）を判定",
        prompt: "確定年金と生命年金の差を、死亡時点ごとの残存確定年金に分けた式（D）は？",
        choices: [{ label: "正しい" }, { label: "誤り" }],
        correct: 0,
        explanation: "差は各時点で死亡して失われる将来支払の現価。死亡確率 Cₓ₊t₋₁/Dₓ と残存年金 äₙ₋t の積を合計した式になる。",
        wrongHint: "「生存しなかったため受け取れない支払い」を、死亡年ごとに分解して考えよう。",
      },
      {
        phase: "JUDGE",
        title: "式（E）を判定",
        prompt: "累減定期保険の式（E）にある R の添字は正しい？",
        choices: [
          { label: "正しい" },
          { label: "誤り。Rₓ₊₁−Rₓ₊ₙ₊₁ が正しい" },
          { label: "誤り。Rₓ₋₁−Rₓ₊ₙ₋₁ が正しい" },
        ],
        correct: 1,
        explanation: "正しくは {nMₓ−(Rₓ₊₁−Rₓ₊ₙ₊₁)}/Dₓ。式（E）は端点が1期ずれている。",
        wrongHint: "死亡保険金は年度末支払。Rで集計する最初と最後の添字を1期先へずらす。",
      },
      {
        phase: "JUDGE",
        title: "正しい式をまとめる",
        prompt: "ここまでの判定から、選ぶべき組は？",
        choices: [
          { label: "（A）（C）（D）" },
          { label: "（A）（B）（C）" },
          { label: "（C）（D）（E）" },
        ],
        correct: 0,
        explanation: "A・C・Dが正しく、Bは1/kの欠落、EはRの添字ずれ。",
        wrongHint: "各式の判定を並べると、正・誤・正・正・誤。",
      },
    ],
  },
  {
    id: 4,
    topic: "保険現価・微分",
    title: "利率微分を級数から追う",
    image: "/exam/2025-q2/q4.webp",
    solutions: ["/exam/2025-q2/s4.webp"],
    finalAnswer: "（J）",
    goal: "Aₓを年金現価で表し、vの微分から加重年金へつなぐ。",
    steps: [
      {
        phase: "MODEL",
        title: "保険現価を年金で表す",
        prompt: "終身保険現価 Aₓ と終身年金現価 äₓ の基本関係は？",
        choices: [
          { label: "Aₓ=1−d·äₓ" },
          { label: "Aₓ=d·äₓ" },
          { label: "Aₓ=1−v·äₓ" },
        ],
        correct: 0,
        explanation: "保険金年度末支払・年金期始払では Aₓ+däₓ=1。",
        wrongHint: "保険と年金を結ぶ基本公式 Aₓ+däₓ=1 を使う。",
      },
      {
        phase: "DERIVE",
        title: "割引因子を利率で微分",
        prompt: "v=1/(1+i)、d=1−v のとき、正しい微分の組は？",
        choices: [
          { label: "dd/di=v²、d(vᵏ)/di=−k·vᵏ⁺¹" },
          { label: "dd/di=−v²、d(vᵏ)/di=k·vᵏ⁻¹" },
          { label: "dd/di=v、d(vᵏ)/di=−vᵏ" },
        ],
        correct: 0,
        explanation: "dv/di=−v²。d=1−vなので dd/di=v²、べき乗には連鎖律を使う。",
        wrongHint: "まず v=(1+i)⁻¹ を微分し、その結果をdとvᵏへ使おう。",
      },
      {
        phase: "DERIVE",
        title: "加重年金を見つける",
        prompt: "äₓの級数を項別微分すると、支払時点kが係数になる。この和をまとめる記号は？",
        choices: [
          { label: "(Iä)ₓ", sub: "増加型の期始払終身生命年金" },
          { label: "(IA)ₓ", sub: "増加型終身保険" },
          { label: "aₓ", sub: "期末払終身生命年金" },
        ],
        correct: 0,
        explanation: "微分で各項に時点kが掛かるため、増加型年金(Iä)ₓが現れる。",
        wrongHint: "微分前は年金の級数。各支払額に1,2,3,…の重みが付いたものを選ぼう。",
      },
      {
        phase: "CALC",
        title: "式を整理して選択肢へ",
        prompt: "d+v=1 と v=1/(1+i) を使って整理した最終式は？",
        choices: [
          { label: "{d·(Iä)ₓ−äₓ}/(1+i)", sub: "選択肢（J）" },
          { label: "{d·(IA)ₓ−äₓ}/(1+i)" },
          { label: "{d·(Iä)ₓ+äₓ}/(1+i)" },
        ],
        correct: 0,
        explanation: "dAₓ/di=−v²äₓ+dv{(Iä)ₓ−äₓ}=v{d(Iä)ₓ−äₓ}。",
        wrongHint: "現れるのは保険ではなく増加型年金。äₓの符号にも注意。",
      },
    ],
  },
  {
    id: 5,
    topic: "返戻金・責任準備金",
    title: "共通部分を消して差だけを見る",
    image: "/exam/2025-q2/q5.webp",
    solutions: ["/exam/2025-q2/s5.webp"],
    finalAnswer: "（G）0.060",
    goal: "第6年度以降の共通給付を消去し、初期5年間の差をαへ集約する。",
    steps: [
      {
        phase: "READ",
        title: "比較する時点を決める",
        prompt: "第6保険年度以降は両商品とも死亡保険金1。したがって第5年度末の準備金は？",
        choices: [
          { label: "₅V⁽¹⁾=₅V⁽²⁾" },
          { label: "₅V⁽¹⁾=0" },
          { label: "₅V⁽¹⁾+₅V⁽²⁾=1" },
        ],
        correct: 0,
        explanation: "第5年度末以降の将来給付が同じなので、将来法で見た準備金も同じ。",
        wrongHint: "過去の給付方法ではなく、第5年度末から先に残っている債務だけを見よう。",
      },
      {
        phase: "MODEL",
        title: "保険種類1を5年進める",
        prompt: "種類1の初期準備金と5年後準備金を結ぶ式は？",
        choices: [
          { label: "D₆₀·₀V⁽¹⁾−P₁(M₆₀−M₆₅)=D₆₅·₅V⁽¹⁾" },
          { label: "D₆₀·₀V⁽¹⁾+P₁(M₆₀−M₆₅)=D₆₅·₅V⁽¹⁾" },
          { label: "D₆₀·₀V⁽¹⁾−P₁(D₆₀−D₆₅)=M₆₅·₅V⁽¹⁾" },
        ],
        correct: 0,
        explanation: "初期5年間に死亡した場合はP₁を返す。その死亡給付現価がP₁(M₆₀−M₆₅)として現れる。",
        wrongHint: "再帰式を計算基数で5年分合計する。死亡給付はM、準備金はDで表す。",
      },
      {
        phase: "DERIVE",
        title: "初期準備金を事業費率で表す",
        prompt: "予定事業費が新契約時のみPに対してαなら、初期準備金は？",
        choices: [
          { label: "₀V=P(1−α)" },
          { label: "₀V=Pα" },
          { label: "₀V=P/(1−α)" },
        ],
        correct: 0,
        explanation: "受け取った営業保険料Pから新契約費αPを差し引いた残額が初期準備金。",
        wrongHint: "保険料Pのうち、契約直後に費消されず残る割合を考えよう。",
      },
      {
        phase: "CALC",
        title: "αだけの式へ整理",
        prompt: "P₁=P₂と共通の₅Vを使ってαについて解くと？",
        choices: [
          { label: "α=1−(M₆₀−M₆₅)/(D₆₀−v⁻⁵D₆₅)=0.06037", sub: "選択肢（G）" },
          { label: "α=(M₆₀−M₆₅)/(D₆₀−D₆₅)=0.282" },
          { label: "α=1−(D₆₀−D₆₅)/(M₆₀−M₆₅)=−2.55" },
        ],
        correct: 0,
        explanation: "数値を代入するとα≈0.06037。最も近い選択肢は0.060。",
        wrongHint: "種類2の初期準備金は v⁻⁵₅V⁽²⁾。D₆₅に付くv⁻⁵を落とさない。",
      },
    ],
  },
  {
    id: 6,
    topic: "多生命年金",
    title: "生存人数ごとの給付を分解する",
    image: "/exam/2025-q2/q6.webp",
    solutions: ["/exam/2025-q2/s6.webp"],
    finalAnswer: "（B）äₓₓ+äᵧᵧ+4äₓᵧ",
    goal: "生存者4人・3人・2人の現価を別々に作り、最後に相殺する。",
    steps: [
      {
        phase: "READ",
        title: "状態ごとの総給付額",
        prompt: "生存者が4人・3人・2人のとき、全員合計の年金額は順に？",
        choices: [
          { label: "6、3、1" },
          { label: "1.5、1、0.5" },
          { label: "6、4、2" },
        ],
        correct: 0,
        explanation: "各人への給付額に生存人数を掛ける。4×1.5=6、3×1=3、2×0.5=1。",
        wrongHint: "問題文の金額は「生存者各人」に支払う額。",
      },
      {
        phase: "MODEL",
        title: "4人全員が生存",
        prompt: "4人全員生存時の給付現価は？",
        choices: [
          { label: "6äₓₓᵧᵧ" },
          { label: "1.5äₓₓᵧᵧ" },
          { label: "4äₓₓᵧᵧ" },
        ],
        correct: 0,
        explanation: "4人全員が生存する確率に、総給付6を掛ける。",
        wrongHint: "前ステップで求めた「総給付額」を使おう。",
      },
      {
        phase: "DERIVE",
        title: "3人生存の部分を包除する",
        prompt: "3人生存時の現価を、3生命・4生命年金で表した式は？",
        choices: [
          { label: "6äₓₓᵧ+6äₓᵧᵧ−12äₓₓᵧᵧ" },
          { label: "3äₓₓᵧ+3äₓᵧᵧ" },
          { label: "6äₓₓᵧ+6äₓᵧᵧ+12äₓₓᵧᵧ" },
        ],
        correct: 0,
        explanation: "xが2人+yが1人、xが1人+yが2人の2型を数え、4人全員生存を重複分として除く。",
        wrongHint: "3生命年金だけだと、4人全員生存している状態も含んでしまう。",
      },
      {
        phase: "DERIVE",
        title: "2人生存の部分を包除する",
        prompt: "2人生存時の現価として正しい式は？",
        choices: [
          { label: "äₓₓ+äᵧᵧ+4äₓᵧ−6äₓₓᵧ−6äₓᵧᵧ+6äₓₓᵧᵧ" },
          { label: "äₓₓ+äᵧᵧ+4äₓᵧ" },
          { label: "2äₓₓ+2äᵧᵧ+2äₓᵧ−2äₓₓᵧ−2äₓᵧᵧ" },
        ],
        correct: 0,
        explanation: "同年齢ペア2通りと異年齢ペア4通りを数え、3人以上生存する重複を包除する。",
        wrongHint: "äₓᵧにはxを1人・yを1人選ぶ4通りがある。3人以上の状態は差し引く。",
      },
      {
        phase: "CALC",
        title: "3状態を合計する",
        prompt: "4人・3人・2人生存時の式をすべて足すと、残る項は？",
        choices: [
          { label: "äₓₓ+äᵧᵧ+4äₓᵧ", sub: "選択肢（B）" },
          { label: "äₓₓ+äᵧᵧ+2äₓᵧ" },
          { label: "6äₓₓᵧᵧ" },
        ],
        correct: 0,
        explanation: "äₓₓᵧ、äₓᵧᵧ、äₓₓᵧᵧの係数がきれいに相殺される。",
        wrongHint: "各項の係数だけを縦に足してみよう。",
      },
    ],
  },
  {
    id: 7,
    topic: "就業不能保険",
    title: "状態別の給付現価を組み上げる",
    image: "/exam/2025-q2/q7.webp",
    solutions: ["/exam/2025-q2/s7.webp"],
    finalAnswer: "（H）0.0061",
    goal: "保険料・就業不能給付・状態別死亡給付を別々に現価化する。",
    steps: [
      {
        phase: "MODEL",
        title: "保険料現価を置く",
        prompt: "保険料は就業者である年度始だけ払う。20年分の保険料現価は？",
        choices: [
          { label: "P·(N₄₀ᵃᵃ−N₆₀ᵃᵃ)/D₄₀ᵃᵃ" },
          { label: "P·(N₄₀ⁱⁱ−N₆₀ⁱⁱ)/D₄₀ⁱⁱ" },
          { label: "P·(M₄₀ᵃᵃ−M₆₀ᵃᵃ)/D₄₀ᵃᵃ" },
        ],
        correct: 0,
        explanation: "保険料支払状態は就業中aa。年金現価なのでNの差をD₄₀ᵃᵃで割る。",
        wrongHint: "保険料は死亡給付ではなく、就業中に毎年払う年金流列。",
      },
      {
        phase: "READ",
        title: "給付を三つに分ける",
        prompt: "給付現価を作るときの三分類は？",
        choices: [
          { label: "就業不能への移行0.5・不能中死亡0.5・就業中死亡1" },
          { label: "就業不能への移行1・不能中死亡1・就業中死亡0.5" },
          { label: "就業中生存0.5・不能中生存0.5・満期1" },
        ],
        correct: 0,
        explanation: "問題文の給付条件を状態遷移と死亡時の状態に分けると、この3本になる。",
        wrongHint: "「いつ」「どの状態で」支払うかを問題文から拾おう。",
      },
      {
        phase: "DERIVE",
        title: "不能中死亡を補正する",
        prompt: "不能中死亡者から、契約開始時点ですでに不能だった仮想集団の死亡を除く項は？",
        choices: [
          { label: "d₄₀₊ₜⁱⁱ−l₄₀ⁱⁱ·ₜ|q₄₀ⁱ" },
          { label: "d₄₀₊ₜⁱⁱ+l₄₀ⁱⁱ·ₜ|q₄₀ⁱ" },
          { label: "d₄₀₊ₜᵃᵃ−l₄₀ᵃᵃ·ₜ|q₄₀ⁱ" },
        ],
        correct: 0,
        explanation: "対象は40歳時点で就業者。計算基数上のii集団から初期ii集団由来の死亡を引き、契約後に不能へ移行した者だけを残す。",
        wrongHint: "この契約の加入者は全員aaからスタートする。",
      },
      {
        phase: "DERIVE",
        title: "M基数へまとめる",
        prompt: "給付現価の分子として正しい形は？",
        choices: [
          { label: "0.5{(M₄₀⁽ⁱ⁾−M₆₀⁽ⁱ⁾)+(M₄₀ⁱⁱ−M₆₀ⁱⁱ)−D₄₀ⁱⁱ(M₄₀ⁱ−M₆₀ⁱ)/D₄₀ⁱ}+M₄₀ᵃᵃ−M₆₀ᵃᵃ" },
          { label: "0.5{M₄₀⁽ⁱ⁾+M₄₀ⁱⁱ}+M₄₀ᵃᵃ" },
          { label: "(N₄₀ⁱⁱ−N₆₀ⁱⁱ)+(N₄₀ᵃᵃ−N₆₀ᵃᵃ)" },
        ],
        correct: 0,
        explanation: "移行給付、不能中死亡の補正、就業中死亡をそれぞれMの差へ変換したもの。",
        wrongHint: "死亡・状態移行の現価にはM、保険料年金にはNを使う。",
      },
      {
        phase: "CALC",
        title: "計算基数を代入する",
        prompt: "上の給付現価を N₄₀ᵃᵃ−N₆₀ᵃᵃ で割った純保険料は？",
        choices: [
          { label: "0.006117", sub: "最も近い選択肢（H）0.0061" },
          { label: "0.005900", sub: "選択肢（G）" },
          { label: "0.006500", sub: "選択肢（J）" },
        ],
        correct: 0,
        explanation: "表の値を代入すると0.006117。選択肢では0.0061が最も近い。",
        wrongHint: "分母は保険料現価のN差。D差ではない。",
      },
    ],
  },
  {
    id: 8,
    topic: "入院給付・分布",
    title: "期待給付日数の比へ落とす",
    image: "/exam/2025-q2/q8.webp",
    solutions: ["/exam/2025-q2/s8.webp"],
    finalAnswer: "（H）1.50",
    goal: "両商品の共通因子を消し、日数区分ごとの期待給付額だけを比較する。",
    steps: [
      {
        phase: "MODEL",
        title: "比で消えるものを見抜く",
        prompt: "Pᴮ/Pᴬを取ると、両商品で共通して消える因子は？",
        choices: [
          { label: "v¹ᐟ²・h・δ・äₓ:ₙ のすべて" },
          { label: "h だけ" },
          { label: "予定利率だけ" },
        ],
        correct: 0,
        explanation: "発生時点、発生率のh、日額δ、生存・保険期間の因子は共通。残るのは入院日数別の給付係数。",
        wrongHint: "両保険料を「共通因子×日数係数」の形にしてから比を取ろう。",
      },
      {
        phase: "CALC",
        title: "商品Aの期待給付日数",
        prompt: "実入院日数をそのまま払うAの係数は？",
        formula: "10hΣᵢ₌₁¹⁰i + 3hΣᵢ₌₁₁³⁰i + hΣᵢ₌₃₁¹²⁰i",
        choices: [
          { label: "8,575h" },
          { label: "12,900h" },
          { label: "6,795h" },
        ],
        correct: 0,
        explanation: "各区間は550h、1,230h、6,795h。合計8,575h。",
        wrongHint: "発生率だけでなく、商品Aは入院日数iも掛ける。",
      },
      {
        phase: "CALC",
        title: "商品Bの30日単位切上げ",
        prompt: "Bの各区間（1–10、11–30、31–60、61–90、91–120日）の係数は？",
        choices: [
          { label: "3,000h、1,800h、1,800h、2,700h、3,600h" },
          { label: "550h、1,230h、1,395h、2,295h、3,195h" },
          { label: "300h、600h、1,800h、2,700h、3,600h" },
        ],
        correct: 0,
        explanation: "たとえば1〜10日は各ケース30日分を払い、10日×30×10h=3,000h。以降も給付日数30・60・90・120を掛ける。",
        wrongHint: "商品Bでは実日数iではなく、その区間の切上げ後日数を全ケースに掛ける。",
      },
      {
        phase: "CALC",
        title: "期待給付額の比を取る",
        prompt: "Bの合計係数12,900hをAの8,575hで割ると？",
        choices: [
          { label: "12,900/8,575=1.5044…", sub: "最も近い選択肢（H）1.50" },
          { label: "8,575/12,900=0.6647…" },
          { label: "(12,900−8,575)/8,575=0.5044…" },
        ],
        correct: 0,
        explanation: "求めるのはPᴮがPᴬの何倍かなのでB/A。1.5044…より1.50。",
        wrongHint: "問題文は「Bの保険料はAのk倍」。分子をBにしよう。",
      },
    ],
  },
];
